### ISSUE TITLE
Empty bytes does not round trip

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#105]
We allow encrypting an empty array, but decrypting fails with an `AesEncryptedDocSizeError`.

The right thing is probably to error on encrypt, but I'm not 100% sure of that. 

I have created a integration test that shows this on [this branch](https://github.com/IronCoreLabs/ironoxide/tree/bug-encrypt-empty-bytes)

**Comment by BobWall23** [comment]
It should be possible to encrypt an empty string - that shouldn't be an error. Output of encrypt should be an IV and a tag (28 total bytes, I think?)

**Comment by clintfred** [comment]
Encrypt was left alone and the decrypt restriction was relaxed.
