### ISSUE TITLE
[SPIKE] Understand tokio threading behavior or native Rust Future replacement

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#11]
As an ironoxide consumer
I want to understand the threading behavior of of ironoxide
so that I can tune the performance (number of threads) in my application.

tokio is used, but a new runtime is created for each API call and there's nothing being done to constrain or define the threading behavior. The goal here is to understand what is being done and know what steps are necessary to make it better.

Changing it to a different approach would be a different issue(s).

**Comment by ernieturner** [comment]
Going to leave this how it is in the hopes that when we need to get around to doing it we'll be able to move over to the standard Rust Future implementation and possibly get rid of all the tokio threading entirely.

**Comment by clintfred** [comment]
We are removing tokio runtime from this library in favor of a full async API #93
