### ISSUE TITLE
[SPIKE] Consider switching to prost for protobuf serialization

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#184]
We should consider switching to from rust-protobuf to https://github.com/danburkert/prost.

We are accumulating [lots of workarounds](https://github.com/IronCoreLabs/ironoxide/blob/master/build.rs) to things working. There also might be better ways to use rust-protobuf too, but our experience with that project hasn't been very good so looking at an alternative makes some sense.

We didn't use prost originally as the project looked very inactive, but I think some bigger rust projects are now behind it and it's very active now.

EDIT: I also see now that rust-protobuf is adding better support for our use case. See https://github.com/stepancheg/rust-protobuf/pull/525

**Comment by giarc3** [comment]
prost is possibly abandoned, but rust-protobuf is continuing to be maintained/improved. In addition, new features have allowed us to remove our workarounds. So we will stick with rust-protobuf for now
