### ISSUE TITLE
publicsuffix can be dropped

### ISSUE THREAD

**Issue by rushmorem** [IronCoreLabs/ironoxide#231]
It seems like this crate is only using `publicsuffix` to take advantage of `publicsuffix::IntoUrl` trait. This trait is no longer available in v2 of the crate. You can use `url::Url::parse` instead and drop  publicsuffix entirely.

**Comment by clintfred** [comment]
@rushmorem Thanks for the heads up. Direct usage of `url` works great.

**Comment by rushmorem** [comment]
You are welcome :)
