### ISSUE TITLE
Implement standard device key format

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#25]
We are going to standardize the DeviceContext/DeviceKeys JSON format across all SDKs. The proposed format (in Typescript) is:

```
{
    deviceId: number;
    accountId: string;
    segmentId: number;
    devicePrivateKey: Base64String;
    // “expanded private key” (both pub/priv)
    signingPrivateKey: Base64String; 
}
```

see: https://github.com/IronCoreLabs/ironnode/issues/27

**Comment by ernieturner** [comment]
Updated to add deviceId to this response structure as well.

**Comment by ernieturner** [comment]
When complete, write up tickets to do this work in java & scala and add to spreadsheet
