### ISSUE TITLE
JWT validation doesn't allow conflicting prefixed and non-prefixed claims

### ISSUE THREAD

**Issue by giarc3** [IronCoreLabs/ironoxide#280]
We currently use `#[serde(alias = "...")]` to allow claims like `sid` or `http://ironcore/sid`. If both are present, however, this will fail as serde sees them as duplicate keys. 

We need to allow for both keys to be present during validation.

**Comment by digitalconnectionsau** [comment]
Hi, 
Thank you for looking at this. If you need anything let me know.
