### ISSUE TITLE
Consider renaming encrypted_data to ciphertext

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#31]
See discussion at https://github.com/IronCoreLabs/ironoxide-java/pull/37#discussion_r310639161

This would apply to both `DocumentEncryptResult` and `DocumentEncryptUnmanagedResult` as well as (possibly) some internal data structures.

If this is done, tickets in ironoxide-java/scala should be created as well.

**Comment by ernieturner** [comment]
Decided this wasn't worth the effort and the naming we have is ok for now.
