### ISSUE TITLE
Every request starts a new client & connection

### ISSUE THREAD

**Issue by jmreardon-yoppworks** [IronCoreLabs/ironoxide#324]
I've observed that every request to the IronCore server starts a new TCP (and therefore TLS connection) resulting in a time-consuming TLS handshake for every request. This appears to be due to ironoxide instantiations a new `Client` for every request:

https://github.com/IronCoreLabs/ironoxide/blob/95405fa3aaa5ce744a7daeac3516285a6da0bdfb/src/internal/rest.rs#L536

Per the reqwest docs, the Client has it's own connection pool and it is expected to be instantiated once and be resued. It's possible the startup time for creating a new Client is slow as well.

**Comment by skeet70** [comment]
We fixed this in #325, though in our benchmarks it didn't make a performance difference either way.
