### ISSUE TITLE
Explore options for better organization of internal/document_api

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#33]
The file internal/document_api/mod.rs has become very large and hard to navigate. We have a couple more functions that are planned, so it will only get worse.

Some ideas: 
* perhaps using sub-modules that split functionality along functional boundaries (similar to what we do in the document_api/requests would be nice? Separate files (per module) could also be used.
* perhaps public result types should be collected in a module? 
* reorganizing of the file might also help. All structs at the top; private functions at the bottom, etc
* make sure all naming is consistent (encrypt_document vs document_get_metadata)

**Comment by ernieturner** [comment]
This has seemingly been subsumed by https://github.com/IronCoreLabs/ironoxide/issues/103
