### ISSUE TITLE
[SPIKE] Investigate PBKDF2 alternatives

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#74]
This issue should result in a write up of the viable PBKDF2 implementations we could use in ironoxide. 

Our primary issue with the current (ring) implementation is that we suspect the performance could be better.

Doesn't have to be pure Rust because IronOxide doesn't need WASM support.

**Comment by zmre** [comment]
Ring is pretty popular. It has constant time ops for some things at least. Saw it referenced in the PBKDF2 context here:

https://rust-lang-nursery.github.io/rust-cookbook/cryptography/encryption.html

**Comment by ernieturner** [comment]
Closing as we weren't using the correct optimization level (`-O3`) made this not a big deal anymore, closing.
