### ISSUE TITLE
Reuse Reqwest Client

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide#85]
As an ironoxide user
I want SDK functions to execute quickly without significant unnecessary overhead

Currently we make a new `Client` for each request in rest.rs. According to [the docs](https://docs.rs/reqwest/0.10.0-alpha.2/reqwest/struct.Client.html) we should be reusing the client to take advantage of connection pooling. Hopefully this will make our requests much faster.

AC:
* [ ] A fixed number of `Client` instances are maintained inside of rest.rs

**Comment by coltfred** [comment]
Removed points and closing for now. Comments are on the mentioned pr. #89
